# config.yaml

path: ./
log_dir: ./logs
workers: 8

vtt_all_step:
  train_dir: ../data/all_step/train
  test_dir: ../data/all_step/test

SMD:
  train_dir: ../data/ServerMachineDataset/train
  test_dir: ../data/ServerMachineDataset/test
  test_label_dir: ../data/ServerMachineDataset/test_label
  interpretation_label_dir: ../data/ServerMachineDataset/interpretation_label


scale: standard

# dataloader parameters
loader_params:
  batch_size: 32
  shuffle: False
  num_workers: 8
  pin_memory: True
  use_val : False

# model parameters
VTTSAT:
  hidden_size: 128
  n_layer: 3
  n_head: 4
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  time_emb: 4
  optim: adamw
  lr: 0.0001
  lradj: type1
  window_size: 350
  feature_num: 12

VTTPAT:
  hidden_size: 128
  n_layer: 3
  n_head: 4
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  time_emb: 4
  optim: adamw
  lr: 0.0001
  lradj: type1
  window_size: 30
  feature_num: 12
